name: PR Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Tests
      uses: ./.github/actions/run-unit-tests
      with:
        python-version: "3.9"
        os: "ubuntu-latest"
        is_pr: "true"
