name: Publish ACA-Py Image
on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        type: string
      platforms:
        description: 'Platforms - Comma separated list of the platforms to support.'
        required: true
        default: linux/amd64,linux/arm64
        type: string
      ref:
        description: 'Optional - The branch, tag or SHA to checkout.'
        required: false
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      platforms:
        required: true
        default: linux/amd64,linux/arm64
        type: string
      ref:
        required: false
        type: string

env:
  # linux/386 platform support has been disabled pending a permanent fix for https://github.com/openwallet-foundation/acapy/issues/2124
  # PLATFORMS: ${{ inputs.platforms || 'linux/amd64,linux/arm64,linux/386' }}
  PLATFORMS: ${{ inputs.platforms || 'linux/amd64,linux/arm64' }}

jobs:
  publish-image:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']

    name: Publish ACA-Py Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || '' }}

      # Adding an extra step to set the image tag explicitly 
      - name: Set Image Tag
        id: set-tag
        run: |
          echo "tag_input=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          echo "release_tag=${{ github.event.release.tag_name || '' }}" >> $GITHUB_OUTPUT
      
          if [[ -n "${{ inputs.tag }}" ]]; then
            echo "IMAGE_TAG=${{ inputs.tag }}" >> $GITHUB_ENV
          elif [[ -n "${{ github.event.release.tag_name }}" ]]; then
            echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "No tag provided. Exiting."
            exit 1
          fi
      
      - name: Gather image info
        id: info
        run: |
          echo "repo-owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/acapy-agent
          tags: |
            type=raw,value=py${{ matrix.python-version }}-${{ env.IMAGE_TAG }}

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: main
          build-args: |
            python_version=${{ matrix.python-version }}
            acapy_version=${{ env.IMAGE_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: ${{ env.PLATFORMS }}

      - name: Setup Image Metadata (BBS)
        id: meta-bbs
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/acapy-agent-bbs
          tags: |
            type=raw,value=py${{ matrix.python-version }}-${{ env.IMAGE_TAG }}

      - name: Build and Push extended Image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: ${{ steps.meta-bbs.outputs.tags }}
          labels: ${{ steps.meta-bbs.outputs.labels }}
          target: main
          build-args: |
            python_version=${{ matrix.python-version }}
            acapy_name=acapy-agent-bbs
            acapy_version=${{ inputs.tag || github.event.release.tag_name }}
            acapy_reqs=[askar,bbs,didcommv2]
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          # Because of BBS, only linux/amd64 is supported for the extended image
          # https://github.com/openwallet-foundation/acapy/issues/2124#issuecomment-2293569659
          platforms: linux/amd64

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
